{% set name = "skypy" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skypy-{{ version }}.tar.gz
  sha256: 7106db578cd5d10f73c0660984bed3defce5e208418697f9c9bfae625c3bd55b

build:
  number: 1
  noarch: python
  entry_points:
    - skypy = skypy.pipeline.scripts.skypy:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - astropy >=4
    - networkx
    - numpy
    - python >=3.6
    - pyyaml
    - scipy <=1.14

test:
  imports:
    - skypy
    - skypy.galaxies
    - skypy.pipeline
    - skypy.utils
  commands:
    - pip check
    - skypy --help
    - pytest --pyargs skypy
  requires:
    - pip
    - pytest-astropy
    - pytest-rerunfailures
    - speclite >=0.14

about:
  home: http://skypy.info
  doc_url: https://skypy.readthedocs.io
  dev_url: https://github.com/skypyproject/skypy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for modelling the Universe.
  description: |
    This package contains methods for modelling the Universe, galaxies and the
    Milky Way. Also included are methods for generating observed data.

extra:
  recipe-maintainers:
    - rrjbca
