{% set name = "skypy" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skypy-{{ version }}.tar.gz
  sha256: 6e1996f00f027254538a999b675a2d66c5fde58e50751e94e49cb0fe00b5bcd8

build:
  number: 0
  noarch: python
  entry_points:
    - skypy = skypy.pipeline.scripts.skypy:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - astropy
    - networkx
    - numpy
    - python >=3.6
    - pyyaml
    - scipy

test:
  imports:
    - skypy
    - skypy.cluster
    - skypy.extern
    - skypy.galaxy
    - skypy.gravitational_wave
    - skypy.halo
    - skypy.pipeline
    - skypy.power_spectrum
    - skypy.supernova
    - skypy.utils
  commands:
    - pip check
    - skypy --help
    - pytest --pyargs skypy
  requires:
    - pip
    - pytest

about:
  home: http://skypy.info
  doc_url: https://skypy.readthedocs.io
  dev_url: https://github.com/skypyproject/skypy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for modelling the Universe.
  description: |
    This package contains methods for modelling the Universe, galaxies and the
    Milky Way. Also included are methods for generating observed data.

extra:
  recipe-maintainers:
    - rrjbca
