{% set name = "skypy" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skypy-{{ version }}.tar.gz
  sha256: d5d493083e31314e5f128cebb5b2b8b1dce4c0e2e58ca10ebd9f7329575bf0dc

build:
  number: 1
  noarch: python
  entry_points:
    - skypy = skypy.pipeline.scripts.skypy:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - astropy >=4
    - networkx
    - numpy
    - python >={{ python_min }}
    - pyyaml
    - scipy

test:
  imports:
    - skypy
    - skypy.galaxies
    - skypy.pipeline
    - skypy.utils
  commands:
    - pip check
    - skypy --help
    - pytest --pyargs skypy
  requires:
    - pip
    - pytest-astropy
    - pytest-rerunfailures
    - speclite >=0.14
    - python {{ python_min }}

about:
  home: http://skypy.info
  doc_url: https://skypy.readthedocs.io
  dev_url: https://github.com/skypyproject/skypy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for modelling the Universe.
  description: |
    This package contains methods for modelling the Universe, galaxies and the
    Milky Way. Also included are methods for generating observed data.

extra:
  recipe-maintainers:
    - rrjbca
